### ISSUE TITLE
Confusing dobot vs responsive dobot

### ISSUE THREAD

**Issue by acacheung** [quinnfield/quinnfield.github.io#2]
our current assignment is dobot, not responsive dobot yet. it looks like responsive dobot is more complete so i'll review that instead, but responsive dobot is a separate assignment for when we make it mobile-friendly

**Comment by quinnfield** [comment]
A couple of us were confused  because we didnt know what this was, so we took the style and formatting out of dubot and put the dubot finalized file into responsive. I can fix it.
