### ISSUE TITLE
Add CSS reset to get rid of extra spacing

### ISSUE THREAD

**Issue by acacheung** [quinnfield/quinnfield.github.io#7]
You are adding the reset to the project, but not including it in your html
https://github.com/quinnfield/quinnfield.github.io/blob/master/dobot/index.html#L9

it should be linked before `style.css` to work properly

**Comment by quinnfield** [comment]
When I add the reset.css its messes up the HTML, how would I fix that.? I linked in before style.css

**Comment by acacheung** [comment]
it messes up the html or css?

**Comment by acacheung** [comment]
you should get something like this:
<img width="1322" alt="screen shot 2016-10-22 at 6 40 47 pm" src="https://cloud.githubusercontent.com/assets/1054686/19623008/1791c73c-9887-11e6-8976-17965e007daa.png">

then you'll need to fix things up again, but now all the spacing has been normalized across browsers

before you add it, there are random margins and paddings to make things look okay without any css. for example chrome adds an 8px margin on body so things aren't flush against the edges of the screen
<img width="1678" alt="screen shot 2016-10-22 at 6 43 03 pm" src="https://cloud.githubusercontent.com/assets/1054686/19623017/7c6c9ea2-9887-11e6-9a71-0b34b734d02a.png">

**Comment by quinnfield** [comment]
Okay exactly what happens. So I will have to customize the reset.css so it doesn't do this?

**Comment by acacheung** [comment]
no leave the reset and fix your `style.css`

**Comment by quinnfield** [comment]
Okay, got it. Thank you!

**Comment by acacheung** [comment]
:)

**Comment by quinnfield** [comment]
Im finding that it would be hard to style some parts with out using a container like the exercise in class. Is that the best way to go?
